import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";
import { CartProvider } from "@/context/CartContext";
import { getServerSession } from "next-auth";
import SessionProvider from '../context/SessionProvider';

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Parafarm",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();

  return (
    <html lang="en">
          <body className={inter.className}>
            <SessionProvider session={session}>
              <Suspense fallback={<Loading/>}>              
                  <CartProvider>
                      {children}
                  </CartProvider>              
              </Suspense>
            </SessionProvider>
          </body>
    </html>
  );
}